import type { RawProduct } from '../types';

export const fixtureCatalog: RawProduct[] = [
  {
    id: 1,
    title: 'Essence Mascara Lash Princess',
    description:
      'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
    category: 'beauty',
    price: 9.99,
    discountPercentage: 10.48,
    rating: 2.56,
    stock: 99,
    tags: ['beauty', 'mascara'],
    brand: 'Essence',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 48,
    shippingInformation: 'Ships in 1 month',
    returnPolicy: '30 days return policy',
    warrantyInformation: '1 week warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara/thumbnail.png',
  },
  {
    id: 2,
    title: 'Eyeshadow Palette with Mirror',
    description:
      'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it is convenient for on-the-go application.',
    category: 'beauty',
    price: 19.99,
    discountPercentage: 18.19,
    rating: 2.86,
    stock: 4,
    tags: ['beauty', 'eyeshadow'],
    brand: 'Glamour Beauty',
    availabilityStatus: 'Low Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 2 weeks',
    returnPolicy: '30 days return policy',
    warrantyInformation: '1 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette/thumbnail.png',
  },
  {
    id: 3,
    title: 'Powder Canister',
    description:
      'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth matte finish.',
    category: 'beauty',
    price: 14.99,
    discountPercentage: 12.5,
    rating: 4.64,
    stock: 89,
    tags: ['beauty', 'face powder'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 3,
    shippingInformation: 'Ships in 1-2 business days',
    returnPolicy: '7 days return policy',
    warrantyInformation: '2 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png',
  },
  {
    id: 6,
    title: 'Calvin Klein CK One',
    description:
      'CK One by Calvin Klein is a classic unisex fragrance known for its fresh and clean scent. It is a versatile fragrance suitable for everyday wear.',
    category: 'fragrances',
    price: 49.99,
    discountPercentage: 1.03,
    rating: 4.85,
    stock: 29,
    tags: ['fragrances', 'perfumes'],
    brand: 'Calvin Klein',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships overnight',
    returnPolicy: '60 days return policy',
    warrantyInformation: '5 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein/thumbnail.png',
  },
  {
    id: 8,
    title: 'Gucci Bloom Eau de Parfum',
    description:
      'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose and jasmine. It is a modern and romantic scent.',
    category: 'fragrances',
    price: 79.99,
    discountPercentage: 8.9,
    rating: 2.69,
    stock: 0,
    tags: ['fragrances', 'perfumes'],
    brand: 'Gucci',
    availabilityStatus: 'Out of Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 3-5 business days',
    returnPolicy: 'No return policy',
    warrantyInformation: '1 month warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom/thumbnail.png',
  },
  {
    id: 12,
    title: 'Knoll Saarinen Executive Conference Chair',
    description:
      'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.',
    category: 'furniture',
    price: 499.99,
    discountPercentage: 15.23,
    rating: 4.07,
    stock: 47,
    tags: ['furniture', 'office chairs'],
    brand: 'Knoll',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 1 week',
    returnPolicy: '60 days return policy',
    warrantyInformation: '5 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Knoll%20Chair/thumbnail.png',
  },
  {
    id: 13,
    title: 'Wooden Bathroom Sink With Mirror',
    description:
      'The Wooden Bathroom Sink with Mirror is a stylish and functional addition to your bathroom, featuring a solid oak countertop and a matching framed mirror.',
    category: 'furniture',
    price: 799.99,
    discountPercentage: 10.62,
    rating: 3.02,
    stock: 95,
    tags: ['furniture', 'bathroom'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 2 weeks',
    returnPolicy: '30 days return policy',
    warrantyInformation: 'Lifetime warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Wooden%20Sink/thumbnail.png',
  },
  {
    id: 20,
    title: 'Apple',
    description:
      'Fresh and crisp apples, perfect for snacking or baking. Sold loose by the kilogram from local orchards.',
    category: 'groceries',
    price: 1.99,
    discountPercentage: 1.42,
    rating: 4.19,
    stock: 137,
    tags: ['fruits'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 5,
    shippingInformation: 'Ships in 1-2 business days',
    returnPolicy: '7 days return policy',
    warrantyInformation: '1 month warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Apple/thumbnail.png',
  },
  {
    id: 23,
    title: 'Green Chili Pepper',
    description:
      'A spicy green chili pepper, ideal for adding heat to your favourite dishes. Harvested and packed the same day.',
    category: 'groceries',
    price: 0.79,
    discountPercentage: 15.5,
    rating: 4.43,
    stock: 61,
    tags: ['vegetables'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 10,
    shippingInformation: 'Ships overnight',
    returnPolicy: 'No return policy',
    warrantyInformation: 'No warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Green%20Chili/thumbnail.png',
  },
  {
    id: 26,
    title: 'Ice Cream',
    description:
      'Creamy vanilla ice cream churned in small batches. Ships frozen in insulated packaging to stay solid in transit.',
    category: 'groceries',
    price: 5.49,
    discountPercentage: 6.11,
    rating: 3.94,
    stock: 8,
    tags: ['desserts'],
    availabilityStatus: 'Low Stock',
    minimumOrderQuantity: 20,
    shippingInformation: 'Ships overnight',
    returnPolicy: 'No return policy',
    warrantyInformation: 'No warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/thumbnail.png',
  },
  {
    id: 40,
    title: 'Attitude Super Leaves Hand Soap',
    description:
      'A plant-based hand soap with a gentle formula. Free of sulfates and suitable for sensitive skin.',
    category: 'skin-care',
    price: 12.99,
    discountPercentage: 3.31,
    rating: 4.61,
    stock: 73,
    tags: ['skin care', 'hand soap'],
    brand: 'Attitude',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 2,
    shippingInformation: 'Ships in 3-5 business days',
    returnPolicy: '30 days return policy',
    warrantyInformation: 'No warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/skin-care/Hand%20Soap/thumbnail.png',
  },
  {
    id: 50,
    title: 'Decoration Swing',
    description:
      'A hanging decorative swing for indoor corners and balconies. Rope-mounted with a reinforced hardwood seat.',
    category: 'home-decoration',
    price: 59.99,
    discountPercentage: 12.02,
    rating: 2.71,
    stock: 52,
    tags: ['home decoration'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 1 week',
    returnPolicy: '90 days return policy',
    warrantyInformation: '6 months warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/home-decoration/Swing/thumbnail.png',
  },
  {
    id: 79,
    title: 'Bamboo Spatula',
    description:
      'Heat resistant and safe for non-stick cookware, this utensil will not scratch your pans. Dishwasher friendly and sustainably sourced.',
    category: 'kitchen-accessories',
    price: 7.99,
    discountPercentage: 5.19,
    rating: 4.71,
    stock: 130,
    tags: ['kitchen accessories'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 4,
    shippingInformation: 'Ships in 1-2 business days',
    returnPolicy: '7 days return policy',
    warrantyInformation: '3 months warranty',
    thumbnail:
      'https://cdn.dummyjson.com/products/images/kitchen-accessories/Bamboo%20Spatula/thumbnail.png',
  },
  {
    id: 80,
    title: 'Black Aluminium Cup',
    description:
      'An insulated cup that keeps drinks cold for hours. Anodised finish resists fingerprints and is dishwasher safe.',
    category: 'kitchen-accessories',
    price: 10.49,
    discountPercentage: 9.75,
    rating: 4.16,
    stock: 84,
    tags: ['kitchen accessories'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 6,
    shippingInformation: 'Ships in 3-5 business days',
    returnPolicy: '30 days return policy',
    warrantyInformation: '1 year warranty',
    thumbnail:
      'https://cdn.dummyjson.com/products/images/kitchen-accessories/Aluminium%20Cup/thumbnail.png',
  },
  {
    id: 91,
    title: 'Rolex Submariner Watch',
    description:
      'The Rolex Submariner is a legendary dive watch with automatic movement and water resistance to 300 metres.',
    category: 'mens-watches',
    price: 13999.99,
    discountPercentage: 0.82,
    rating: 4.94,
    stock: 12,
    tags: ['mens watches', 'luxury'],
    brand: 'Rolex',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 1 week',
    returnPolicy: '90 days return policy',
    warrantyInformation: 'Lifetime warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/mens-watches/Rolex/thumbnail.png',
  },
  {
    id: 100,
    title: 'Classic Sunglasses',
    description:
      'Polarised lenses with full UV400 protection in a lightweight acetate frame. Includes a hard case.',
    category: 'sunglasses',
    price: 29.99,
    discountPercentage: 14.36,
    rating: 3.11,
    stock: 41,
    tags: ['sunglasses'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 2,
    shippingInformation: 'Ships in 1-2 business days',
    returnPolicy: '30 days return policy',
    warrantyInformation: '6 months warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/sunglasses/Classic/thumbnail.png',
  },
  {
    id: 110,
    title: 'Black Women Gown',
    description:
      'A floor-length evening gown in matte crepe with a concealed zip. Lined bodice and a subtle side slit.',
    category: 'womens-dresses',
    price: 78.99,
    discountPercentage: 11.28,
    rating: 3.44,
    stock: 26,
    tags: ['womens dresses'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 2 weeks',
    returnPolicy: '30 days return policy',
    warrantyInformation: '3 months warranty',
    thumbnail:
      'https://cdn.dummyjson.com/products/images/womens-dresses/Black%20Gown/thumbnail.png',
  },
  {
    id: 121,
    title: 'Apple MacBook Pro 14 Inch Space Grey',
    description:
      'The MacBook Pro 14 Inch pairs a Liquid Retina XDR display with all-day battery life. Built for demanding creative and engineering workloads.',
    category: 'laptops',
    price: 1999.99,
    discountPercentage: 8.79,
    rating: 3.65,
    stock: 83,
    tags: ['laptops'],
    brand: 'Apple',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 3-5 business days',
    returnPolicy: '30 days return policy',
    warrantyInformation: '1 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/laptops/MacBook%20Pro/thumbnail.png',
  },
  {
    id: 122,
    title: 'Dell XPS 13',
    description:
      'A compact ultrabook with an InfinityEdge display and a machined aluminium chassis. Configured with 16GB of memory.',
    category: 'laptops',
    price: 999.99,
    discountPercentage: 19.14,
    rating: 4.42,
    stock: 5,
    tags: ['laptops'],
    brand: 'Dell',
    availabilityStatus: 'Low Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 1 week',
    returnPolicy: '60 days return policy',
    warrantyInformation: '2 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/laptops/Dell%20XPS%2013/thumbnail.png',
  },
  {
    id: 123,
    title: 'Huawei Matebook X Pro',
    description:
      'A slim productivity notebook with a 3K touch display and a fanless thermal design for quiet operation.',
    category: 'laptops',
    price: 1399.99,
    discountPercentage: 17.86,
    rating: 3.28,
    stock: 0,
    tags: ['laptops'],
    brand: 'Huawei',
    availabilityStatus: 'Out of Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 1 month',
    returnPolicy: '7 days return policy',
    warrantyInformation: '1 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/laptops/Matebook%20X%20Pro/thumbnail.png',
  },
  {
    id: 131,
    title: 'iPad Mini 2021 Starlight',
    description:
      'A compact tablet with an 8.3 inch Liquid Retina display and support for the second generation stylus.',
    category: 'tablets',
    price: 599.99,
    discountPercentage: 4.55,
    rating: 4.02,
    stock: 37,
    tags: ['tablets'],
    brand: 'Apple',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships overnight',
    returnPolicy: '30 days return policy',
    warrantyInformation: '1 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini/thumbnail.png',
  },
  {
    id: 141,
    title: 'iPhone 13 Pro',
    description:
      'A flagship handset with a ProMotion display and a triple camera system tuned for low light photography.',
    category: 'smartphones',
    price: 399.99,
    discountPercentage: 12.96,
    rating: 4.71,
    stock: 68,
    tags: ['smartphones'],
    brand: 'Apple',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 1-2 business days',
    returnPolicy: '30 days return policy',
    warrantyInformation: '1 year warranty',
    thumbnail:
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/thumbnail.png',
  },
  {
    id: 142,
    title: 'Samsung Galaxy S10',
    description:
      'A dynamic AMOLED handset with an ultrasonic in-display fingerprint reader and reverse wireless charging.',
    category: 'smartphones',
    price: 419.99,
    discountPercentage: 7.4,
    rating: 3.86,
    stock: 54,
    tags: ['smartphones'],
    brand: 'Samsung',
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 3-5 business days',
    returnPolicy: '60 days return policy',
    warrantyInformation: '2 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Galaxy%20S10/thumbnail.png',
  },
  {
    id: 148,
    title: 'Generic Motorcycle',
    description:
      'A road-legal 400cc motorcycle with disc brakes front and rear. Delivered crated and requires assembly.',
    category: 'motorcycle',
    price: 3999.99,
    discountPercentage: 13.11,
    rating: 2.94,
    stock: 22,
    tags: ['motorcycle'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 1 month',
    returnPolicy: 'No return policy',
    warrantyInformation: '3 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Bike/thumbnail.png',
  },
  {
    id: 155,
    title: 'Basketball',
    description:
      'An indoor and outdoor composite leather basketball, official size seven, shipped inflated and game ready.',
    category: 'sports-accessories',
    price: 19.99,
    discountPercentage: 8.44,
    rating: 4.51,
    stock: 118,
    tags: ['sports accessories'],
    availabilityStatus: 'In Stock',
    minimumOrderQuantity: 10,
    shippingInformation: 'Ships in 2 weeks',
    returnPolicy: '90 days return policy',
    warrantyInformation: '6 months warranty',
    thumbnail:
      'https://cdn.dummyjson.com/products/images/sports-accessories/Basketball/thumbnail.png',
  },
  {
    id: 172,
    title: 'Dodge Hornet GT Plus',
    description:
      'A compact performance crossover with all-wheel drive and an adaptive suspension package.',
    category: 'vehicle',
    price: 36999.99,
    discountPercentage: 2.16,
    rating: 4.28,
    stock: 6,
    tags: ['vehicle'],
    brand: 'Dodge',
    availabilityStatus: 'Low Stock',
    minimumOrderQuantity: 1,
    shippingInformation: 'Ships in 1 month',
    returnPolicy: '7 days return policy',
    warrantyInformation: '5 year warranty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet/thumbnail.png',
  },
];

// Kept out of fixtureCatalog on purpose: several suites assert exact enum coverage and
// "every fixture product is known-good" over that array, and it is shared by the tool,
// memory, integration, and eval suites. Drift scenarios belong in their own corpus.
export const productWithUnknownCategory: RawProduct = {
  ...fixtureCatalog[0],
  id: 9001,
  title: 'Quantum Flux Capacitor',
  category: 'electronics',
};

export const productWithUnknownLogistics: RawProduct = {
  ...fixtureCatalog[0],
  id: 9002,
  title: 'Teleporting Sock Drawer',
  shippingInformation: 'Ships via carrier pigeon',
  returnPolicy: 'Returns accepted in another dimension',
  warrantyInformation: 'Eternal warranty',
};

export const fixtureCatalogWithUnknownValues: RawProduct[] = [
  ...fixtureCatalog,
  productWithUnknownCategory,
  productWithUnknownLogistics,
];
